# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    config.vm.box = "ubuntu/trusty64"

    config.vm.network :forwarded_port, guest: 4369,  host: 4369,  auto_correct: true # epmd
    config.vm.network :forwarded_port, guest: 5672,  host: 5672,  auto_correct: true # AMQP
    config.vm.network :forwarded_port, guest: 15672, host: 15672, auto_correct: true # management plugin

    config.vm.network :private_network, ip: "192.168.42.10"

    config.vm.provision 'shell', path: 'provision.sh'

end