# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    config.vm.box = "ubuntu/trusty64"

    config.vm.network :forwarded_port, guest: 27017, host: 27017, auto_correct: true # mongod

    config.vm.network :private_network, ip: "192.168.42.11"

    config.vm.provision 'shell', path: 'provision.sh'

end