# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    if Vagrant.has_plugin?("vagrant-cachier")
        config.cache.scope = :box
    end

    config.vm.hostname = "mongodb"

    config.vm.box = "ubuntu/trusty64"

    config.vm.network :forwarded_port, guest: 27017, host: 27017, auto_correct: true # mongo

    config.vm.network :private_network, ip: "192.168.42.11"

    config.vm.provider 'virtualbox' do |v|
        v.customize ['modifyvm', :id, '--name', 'trusty64-mongodb']
        v.customize ['modifyvm', :id, '--cpus', '2']
        v.customize ['modifyvm', :id, '--memory', 1024]
    end

    config.vm.provision 'shell', path: 'provision.sh'

end