server:
  type: default
  maxThreads: 32
  applicationConnectors:
    - type: http
      port: 9080
      maxRequestHeaderSize: 8KiB
      maxResponseHeaderSize: 8KiB
      acceptorThreads: 2
      selectorThreads: 2
  adminConnectors:
    - type: http
      port: 9081
  gzip:
    enabled: true
    bufferSize: 32KiB

logging:
  level: INFO
  loggers:
    "de.jeha.kame": DEBUG

crawler-service:
  url: http://localhost:8080/crawl

scheduler:
  instanceId: default
  jobStore: org.quartz.simpl.RAMJobStore
  threadPool: org.quartz.simpl.SimpleThreadPool
  threadCount: 4
