apiMetadata:
    title: kame crawler-service
    contact: jenshadlich@googlemail.com

spring:
  appContextType: web
  configLocationsType: classpath

  configLocations:
    - dropwizard-spring.xml

  resources:
    - crawlResource

  healthChecks:
    - databaseHealthCheck

  enabledJerseyFeatures:
    - com.sun.jersey.config.feature.CanonicalizeURIPath

  disabledJerseyFeatures:
    - com.sun.jersey.config.feature.DisableWADL
