server:
  type: default
  maxThreads: 32
  applicationConnectors:
    - type: http
      port: 8080
      maxRequestHeaderSize: 8KiB
      maxResponseHeaderSize: 8KiB
      acceptorThreads: 2
      selectorThreads: 2
  gzip:
    enabled: true
    bufferSize: 32KiB

logging:
  level: INFO
  loggers:
    "de.jeha.kame": DEBUG

mongoDb:
  url: localhost:27017
  database: crawler-service

crawler:
  userAgent: Mozilla/5.0 (compatible; Kamebot/0.1)

documentStore:
  type: file
  path: ./documents
